import { test } from "node:test";
import assert from "node:assert/strict";

import { parseDefaultGatewayHex, parseNameserver } from "../daemon-client.js";

// /proc/net/route uses little-endian hex for the gateway. The default route
// is the row whose Destination is 00000000. Gateway 0100A8C0 → 192.168.0.1.
const PROC_NET_ROUTE = `Iface\tDestination\tGateway\tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT
eth0\t00000000\t0100A8C0\t0003\t0\t0\t0\t00000000\t0\t0\t0
eth0\t0000A8C0\t00000000\t0001\t0\t0\t0\t00FFFFFF\t0\t0\t0
`;

test("parseDefaultGatewayHex decodes the little-endian default gateway", () => {
  assert.equal(parseDefaultGatewayHex(PROC_NET_ROUTE), "192.168.0.1");
});

test("parseDefaultGatewayHex skips the on-link route with a 0.0.0.0 gateway", () => {
  // A WSL2 host typically shows the Windows host as the gateway, e.g.
  // 172.x.x.1. Gateway 01803AAC → 172.58.128.1.
  const route = `Iface\tDestination\tGateway\tFlags
eth0\t00000000\t01803AAC\t0003
`;
  assert.equal(parseDefaultGatewayHex(route), "172.58.128.1");
});

test("parseDefaultGatewayHex returns null when there is no default route", () => {
  const route = `Iface\tDestination\tGateway\tFlags
eth0\t0000A8C0\t00000000\t0001
`;
  assert.equal(parseDefaultGatewayHex(route), null);
});

test("parseDefaultGatewayHex returns null on malformed input", () => {
  assert.equal(parseDefaultGatewayHex(""), null);
  assert.equal(parseDefaultGatewayHex("garbage\nrows\n"), null);
});

test("parseNameserver returns the first nameserver IP", () => {
  const resolv = `# generated by WSL
nameserver 172.58.128.1
nameserver 8.8.8.8
`;
  assert.equal(parseNameserver(resolv), "172.58.128.1");
});

test("parseNameserver tolerates leading whitespace and returns null when absent", () => {
  assert.equal(parseNameserver("  nameserver 10.0.0.1\n"), "10.0.0.1");
  assert.equal(parseNameserver("search localdomain\n"), null);
});
